#!/bin/bash

argc=$#
run="$1"
main="$2"

function build {
	compiler="javac $1/src/*.java -d $1/bin/"
	mkdir -p $1/bin/

	if [ $argc -eq 0 ]; then
		echo "-------------------------------------"
		echo "$compiler"
		eval $compiler
		
		if [ -z "$2" ]; then
			echo "MAIN: $1"
		else
			echo "MAIN: $2"
		fi
		if ! [ -z "$3" ]; then
			echo "ANOTHER MAIN: $3"
			echo "Usage: ./compile-or-run $1 $3"
		fi
		echo "-------------------------------------"
	else
	if [[ "$run" == "$1" ]]; then
		echo "-------------------------------------"
		echo "$compiler"
		eval $compiler
		if [ -z "$2" ]; then
			compiler="java -cp $1/bin/ $1"
		else
			if [ -z "$main" ]; then
				compiler="java -cp $1/bin/ $2"
			else
				compiler="java -cp $1/bin/ $main"
			fi
		fi
		echo "$compiler"
		echo "-------------------------------------"
		if ! [ -z "$3" ]; then
			echo "ANOTHER MAIN: $3"
			echo "Usage: ./compile-or-run $1 $3"
			echo "-------------------------------------"
		fi
		eval $compiler
		
		echo -e "\n-------------------------------------"
		exit
	fi
	fi
}

build BubbleWorld
build FlowersOfLife Main
build Hopper Main
build LastfmPlaylist LFMPlaylistMakerUI
build MultiplayerGame GameServer GameClient
build OrbAvoider Main
build Organisms Main
build Particles Main
build SliderTanks MainClass
build TicTacToe
build Units Main
build VariousJavaPrograms Elevator GraphDFS

echo "USAGE: ./compile-or-run <project-directory-name> <main-class-name>"
echo "(NO SLASHES)"
